console.log('<img src="url">'); //=> "<img src="url">"
console.log("<img src=\"url\">"); //=> "<img src="url">"
console.log("hello' world"); //=> "hello\' world"
console.log("hello\" world"); //=> "hello" world"
console.log("hello\' world"); //=> "hello\' world"
console.log('hello\nworld'); //=> "hello\nworld"
console.log('I \u2661 JavaScript!'); //=> "I ♡ JavaScript!"